version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  web:
    image: nginx
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
